const FILESYSTEM_COLUMN_WIDTHS = {
	NAME: 8,
	TYPE: 2,
	SIZE: 2,
	DATE_ADDED: 4
};

const FILESYSTEM_SORT_MODES = {
	NAME: 0,
	TYPE: 1,
	SIZE: 2,
	DATE_ADDED: 3
};

const TRANSFER_LIST_COLUMN_WIDTHS = {
	NAME: 6,
	PROGRESS: 4,
	STATUS: 1.5,
	EXTRA: 1.5 // Special column with no header text
};

const TRANSFER_STATUS = {
	WAITING: 0,
	DOWNLOADING: 1,
	UPLOADING: 2,
	FINISHED: 3,
	FAILED: 4
}

export {
	FILESYSTEM_COLUMN_WIDTHS,
	FILESYSTEM_SORT_MODES,
	TRANSFER_LIST_COLUMN_WIDTHS,
	TRANSFER_STATUS
};
